# api-gateway/Dockerfile
FROM python:3.10-alpine

WORKDIR /code

# Install required packages
RUN apk add --no-cache gcc musl-dev linux-headers libffi-dev openssl-dev python3-dev

# Install Docker SDK
RUN pip install docker flask requests

COPY app.py .

EXPOSE 8197

CMD ["python", "app.py"]