image: docker:20.10.16

services:
  - docker:20.10.16-dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"

stages:
  - lint
  - test
  - build
  - deploy

.python-setup: &python-setup
  before_script:
    - python -m pip install --user --upgrade pip
    - pip install --user -r tests/requirements.txt

test-api:
  stage: test
  image: python:3.10-slim
  <<: *python-setup
  script:
    - apt-get update && apt-get install -y gcc
    - python -m pytest tests/ -v
  cache:
    paths:
      - .pip-cache/
    key: "${CI_JOB_NAME}"

build-images:
  stage: build
  script:
    - docker compose build

deploy-staging:
  stage: deploy
  script:
    - docker compose down --remove-orphans
    - docker compose up -d
  environment:
    name: staging
  only:
    - develop

deploy-production:
  stage: deploy
  script:
    - docker compose down --remove-orphans
    - docker compose up -d
  environment:
    name: production
  only:
    - main
  when: manual