# Consider modifying your pipeline to be more cross-platform
test-api:
  stage: test
  image: python:3.10-slim
  before_script:
    - pip install -r tests/requirements.txt
  script:
    - python -m pytest tests/test_api_gateway.py
  cache:
    paths:
      - .pip-cache/
    key: "${CI_JOB_NAME}"

# Ensure deploy stages are platform-agnostic
deploy-staging:
  stage: deploy
  script:
    - docker-compose down --remove-orphans
    - docker-compose up -d
  environment:
    name: staging
  only:
    - develop

deploy-production:
  stage: deploy
  script:
    - docker-compose down --remove-orphans
    - docker-compose up -d
  environment:
    name: production
  only:
    - main
  when: manual
