services:
  service1-1:
    build:
      context: ./service1
    networks:
      - app-network
    depends_on:
      - service2

  service1-2:
    build:
      context: ./service1
    networks:
      - app-network
    depends_on:
      - service2

  service1-3:
    build:
      context: ./service1
    networks:
      - app-network
    depends_on:
      - service2

  service2:
    build:
      context: ./service2
    networks:
      - app-network

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8197:8197"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network
    depends_on:
      - nginx

  nginx:
    image: nginx:alpine
    ports:
      - "8198:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/html:/usr/share/nginx/html:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
    networks:
      - app-network
    depends_on:
      - service1-1
      - service1-2
      - service1-3

networks:
  app-network:
    driver: bridge